export const Users = [
  {
    id: 1,
    profilePicture: "assets/person/a.jpeg",
    userName: "Taylor Swift",
  },
  {
    id: 2,
    profilePicture: "assets/person/b.jpeg",
    userName: "Tony Stark",
  },
  {
    id: 3,
    profilePicture: "assets/person/c.jpeg",
    userName: "Cardi Bi",
  },
  {
    id: 4,
    profilePicture: "assets/person/d.jpeg",
    userName: "Billie Ellish",
  },
  {
    id: 5,
    profilePicture: "assets/person/e.jpeg",
    userName: "Kendel Jenner",
  },
  {
    id: 6,
    profilePicture: "assets/person/f.jpeg",
    userName: "Jenifer lawerence",
  },
  {
    id: 7,
    profilePicture: "assets/person/g.jpeg",
    userName: "Bruno Mars",
  },
  {
    id: 8,
    profilePicture: "assets/person/h.jpeg",
    userName: "Adrina Lima",
  },
  {
    id: 9,
    profilePicture: "assets/person/i.jpeg",
    userName: "Rihanna",
  },
  {
    id: 10,
    profilePicture: "assets/person/j.jpeg",
    userName: "Salena Gomez",
  },
];

export const Posts = [
  {
    id: 1,
    desc: "Life is a Journey",
    photo: "assets/post/a.jpeg",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 9,
  },
  {
    id: 2,
    desc: "2 Egg's a day keeps the Doctor away!",
    photo: "assets/post/b.jpeg",
    date: "3 mins ago",
    userId: 2,
    like: 12,
    comment: 9,
  },
  {
    id: 3,
    desc: "Nauture is Beautiful",
    photo: "assets/post/c.jpeg",
    date: "15 Feburary, 2023",
    userId: 3,
    like: 168,
    comment: 9,
  },
  {
    id: 4,
    photo: "assets/post/d.jpeg",
    date: "2 years ago",
    userId: 4,
    like: 38,
    comment: 9,
  },
  {
    id: 5,
    desc: "Old School",
    photo: "assets/post/e.jpeg",
    date: "3 Hour's ago",
    userId: 5,
    like: 32,
    comment: 221,
  },
  {
    id: 6,
    desc: "Meoow",
    photo: "assets/post/f.jpeg",
    date: "2 weeks ago",
    userId: 6,
    like: 32,
    comment: 306,
  },
  {
    id: 7,
    desc: "Love",
    photo: "assets/post/g.jpeg",
    date: "17 mins ago",
    userId: 7,
    like: 378,
    comment: 22,
  },
  {
    id: 8,
    photo: "assets/post/h.jpeg",
    date: "22 October, 2022",
    userId: 8,
    like: 390,
    comment: 0,
  },
  {
    id: 9,
    desc: "Soul-Mate",
    photo: "assets/post/i.jpeg",
    date: "30 April 2023",
    userId: 9,
    like: 32,
    comment: 16,
  },
  {
    id: 10,
    photo: "assets/post/j.jpeg",
    date: "11 mins ago",
    userId: 10,
    like: 812,
    comment: 17,
  },
];
